### PR TITLE
Added new Getting started section

### PR DESCRIPTION
**Pull request by levimcg**
This PR adds a new getting started section to the docs to help us prepare for the upcoming workshop.

After having some offline conversations we realized that it would be helpful to have a logical, dedicated place to put some more focused documentation around Rivet's Sass variables and other introductory content. I've created a new _Getting started_ Hugo section and broke up the old _Components_ page into a couple of new, more focused pages—one about getting started with downloads, and one about using the npm package.

To-dos:

- [x] Review Sass variables to make sure the way they are displayed is readable enough
- [x] See about adding better support for Sass/SCSS syntax highlighting
- [x] Flesh out intro instruction on the `/getting-started/sass/` page to include more info about different ways to use Rivet's Sass files.

### CODE REVIEW

**Comment by levimcg** [comment]
I think this is ready to go. @scottanthonymurray would you mind having a look to make sure this is similar to what you had in mind for documenting the Sass?

**Comment by scottanthonymurray** [comment]
@levimcg Thanks for putting this together! The split between information and getting started sections seems intuitive to me, I'll defer to others on the IA implications but it made sense to me.

What are your thoughts on just including the list of the variables themselves, and not including their values, the Sass map that helps generate them, etc? I like the simplicity of this approach and would like to encourage people to think about the variables in abstract, rather than worry about the specific values they represent. 

On the other hand I imagine there are plenty of situations where a developer might need to know what specific value a variable represents, or maybe the differences between the variables are hard to visualize without some grounding in a "real" value.

I'm torn on this one 🙃 Either way I think this will be really helpful for folks, thank you!

**Comment by levimcg** [comment]
Yes! I thought the same thing about the variable names only vs. variables and values. I agree, that including the maps might be a bit much.

**Comment by levimcg** [comment]
@scottanthonymurray I made some updates based on your feedback. I feel pretty good about his if you want to pull it down and have a look.

**Pull request merged**
